### ISSUE TITLE
Add ability to answer to direct messages

### ISSUE THREAD

**Issue by Scratch-net** [shaunburdick/slack-jirabot#11]
Hi and thanks for the bot!
It works perfect when I type a JIRA issue in channel but does not respond if I message to bot directly. Could you please implement it if possible?

**Comment by shaunburdick** [comment]
Sure! I'll look into when I get some time.

**Comment by Scratch-net** [comment]
Big thanks!
Also, would be nice to have a "mini" mode when only Issue's title (or predefines set of fields like "title, status") is shown instead of a big message that takes 1/4 of the screen which is annoying if used often.

**Comment by shaunburdick** [comment]
Give [library-testing-update](https://github.com/shaunburdick/slack-jirabot/tree/library-testing-update) branch a shot. I don't have a JIRA instance to test this at the moment. 

Add `response: 'minimal'` to your config under jira or set the env `JIRA_RESPONSE=minimal` to get the minimal response (no fields)
Also give direct message a shot, it should reply to a DM now.

**Comment by Scratch-net** [comment]
Fantastic! Works like a charm.
