### ISSUE TITLE
Deal with Jira formatting

### ISSUE THREAD

**Issue by Scratch-net** [shaunburdick/slack-jirabot#13]
The only thing left is jira formatting which is I guess will be tricky to implement. For example:

```
h2. Background
...
```

i mean this one:
https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all

We can at least remove those ugly formatting tags via search & replace, I think it's the easiest workaround

Or use smth like https://www.npmjs.com/package/jira2md

**Comment by shaunburdick** [comment]
Yeah, Slack accepts markdown so I will try jira2md for the description to see if it comes out well.

**Comment by shaunburdick** [comment]
Give [handle-jira-formatting](https://github.com/shaunburdick/slack-jirabot/tree/handle-jira-formatting) branch a shot and let me know if that works.

**Comment by Scratch-net** [comment]
Looks like slack cannot markdown. 

```
Was:
h4. Background 

Became: 
#### Background 

Was:
+Given+
Became:
<ins>Given</ins>
```

https://get.slack.help/hc/en-us/articles/202288908-Formatting-your-messages

**Comment by shaunburdick** [comment]
yeah, I may have to do some formatting of my own.

**Comment by shaunburdick** [comment]
"stole" some regex form jira2md and updated result to match what I can do in Slack:

```
h1. Heading
Foo foo _foo_ foo foo foo
* Bulleted List
** Indented more
* Indented less

# Numbered List
## Indented more
# Indented less

||heading 1||heading 2||
|col A1|col B1|
|col A2|col B2|

Bold: *boldy*
Italic: _Italicy_
Monospace: {{$code}}
Citations: ??citation??
Subscript: ~subscript~
Strikethrough: -strikethrough-
Code: {code}some code{code}
Quote: {quote}quoted text{quote}
No Format: {noformat}pre text{noformat}
Unnamed Link: [http://someurl.com]
Named Link: [Someurl|http://someurl.com]
Blockquote: 
bq. This is quoted
Color: {color:white}This is white text{color}
Panel: {panel:title=foo}Panel Contents{panel}
```

becomes

``````
* Heading*
Foo foo _foo_ foo foo foo
• Bulleted List
 • Indented more
• Indented less

1. Numbered List
 1. Indented more
1. Indented less

|heading 1|heading 2|
| --- | --- |
|col A1|col B1|
|col A2|col B2|

Bold: *boldy*
Italic: _Italicy_
Monospace: `$code`
Citations: _-- citation_
Subscript: ~~subscript~~
Strikethrough: ~strikethrough~
Code: ```some code```
Quote: ```quoted text```
No Format: ```pre text```
Unnamed Link: <http://someurl.com>
Named Link: <http://someurl.com|Someurl>
Blockquote: 
> This is quoted
Color: This is white text
Panel: 
| foo |
| --- |
| Panel Contents |
``````

I'm going to have to get a little fancy when it comes to ordered lists but I'm out of time for now.

**Comment by shaunburdick** [comment]
Ok, got numbered lists working.
Slack doesn't have an equivalent for sub/superscript or inserts :-/
So I left inserts (+insert+) alone and used the latex readable format for sub/superscript:
http://orgmode.org/manual/Subscripts-and-superscripts.html
Subscript: _subscript
Superscript: ^superscript

**Comment by Scratch-net** [comment]
Nice! Seems to be working except one little tiny thing. Strings that are wrapped in tags should be extra trimmed beforehand, otherwise formatting won't work with extra spaces and we'll see thing like

```
* Background *
```

**Comment by Scratch-net** [comment]
Also, in one of the tickets

```
-Implement-
```

turned into

```
~Implement-
```

in slack. The ticket started with -Implement-

**Comment by shaunburdick** [comment]
Ok, I added some regex adjustments to handle poorly formatted input (ie: `* bold *` will become `*bold*`)
the `~Implement-` one I can't seem to replicate. Try it again with my new push and if it happens, email me the raw input and I will take a look.

**Comment by Scratch-net** [comment]
Fantastic! All works perfectly, thank you very much.
