### ISSUE TITLE
Some extra formatting bugs

### ISSUE THREAD

**Issue by Scratch-net** [shaunburdick/slack-jirabot#16]
Hi again and sorry for bugging. We faced some other bugs with jira formatting syntax when using lists.

Consider the following jira ticket:

```
h2.Acceptance Criteria
- test  /api/get-my-info 
- When a filter is selected it shows on the ribbon

h2.Technical tasks
- build the interface
- build the API
- build the filter button (and close icon)
- something else
```

This is how it looks in slack:
![image](https://cloud.githubusercontent.com/assets/7219414/15326895/1317c4ee-1c69-11e6-8297-00b5e2f79e66.png)

and this is how it looks in Jira:
![image](https://cloud.githubusercontent.com/assets/7219414/15326848/eb9179d8-1c68-11e6-9a96-ffdcca4573fa.png)

**Comment by shaunburdick** [comment]
I only account for (*) when doing an unordered list. https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=lists

In the short term you can switch them to (*) and it should work.

**Comment by Scratch-net** [comment]
Sorry, there's too many tickets to fix, (about 100), I cannot do it manually

**Comment by shaunburdick** [comment]
That's ok, I was just suggesting it as a fix until I can get some code in to account for that.
I think it will be pretty easy, I will find some time tonight (EDT) to fix it up.

**Comment by Scratch-net** [comment]
Thank you so much

**Comment by shaunburdick** [comment]
I think I see another bug in there too where `get-my-info` is getting changed to `get~my~info`

**Comment by shaunburdick** [comment]
ok, try the [bugfix/dash-unordered-list](https://github.com/shaunburdick/slack-jirabot/tree/bugfix/dash-unordered-list) and see if that fixes it for you.

**Comment by Scratch-net** [comment]
It's working, thanks a lot!

**Comment by shaunburdick** [comment]
Sweet, merging!
