### ISSUE TITLE
Guide to integrate this?

### ISSUE THREAD

**Issue by altsanz** [shaunburdick/slack-jirabot#19]
Hi!

I don't fully understand how this can be integrated without running on local. Is there a Slack Guide or something? I made a search but found nothing.

Thanks in advance,

**Comment by shaunburdick** [comment]
This is a self hosting solution (at the moment)
I did that so users who self-host their JIRA instance behind a corporate firewall could still use this by setting the bot up in a place that can reach their JIRA.

I have instructions in the README on how to launch this. I also provide a docker image if you want to use that (it's what I personally use). Another option could be adding a Procfile and putting it up on Heroku.

Is this what you mean by integration?

**Comment by altsanz** [comment]
Yes, the self hosting solution is what I was missing, and also what kills me. Have you think on making it official on Slack? Is such a great idea, and I would install it for our team.

**Comment by shaunburdick** [comment]
I have thought about it. I hesitate as it would cost me money and I'm not looking to get into the business of hosting other folks stuff.
I've noticed some places that will host it for me for cheap/free so I've been reconsidering. I would have to retool it a bit to support multiple instances, but that's not hard.

If you'd like, you can use the slack bot [nextup.guru](http://nextup.guru/) stole from me and hosted, but they mention they may try to recoup hosting costs from their users and I don't support theft and profiteering. ¯\_(ツ)_/¯

**Comment by altsanz** [comment]
If you go into it, just I would like to know it ;)

Thank you very much for your time and your work
