### ISSUE TITLE
Good bot, can you add timezone of slack channel?

### ISSUE THREAD

**Issue by JaminShanti** [shaunburdick/slack-jirabot#20]
This is a great bot, can you add timezone of slack channel?

**Comment by shaunburdick** [comment]
TZ if Slack Channel? I'm sorry but I don't quite understand.
Are you looking to have the times adjusted to that timezone or just displayed?

**Comment by JaminShanti** [comment]
The slack channel posts have the local time zone.  I believe the bot is writing UTC for issue.fields.updated value.

**Comment by shaunburdick** [comment]
Hmm I will look to see if Slack provides some localization feature for date/times. I do not believe the channel has a TZ, it's is unique per user.

**Comment by shaunburdick** [comment]
So I did some research. It doesn't seem that Slack communicates a Timezone for either the Channel (https://api.slack.com/types/channel) or Message (https://api.slack.com/events/message) nor do they provide formatting to convert a date to local (https://api.slack.com/docs/message-formatting). I won't be able to format the message to the user's tz as multiple user could have different values.

The bot is actually used the `calendar` method from moment to give you a (time from...) type display.  All I'm doing is allowing moment to parse the date/time from JIRA then doing a compare. That's probably the best I can do at the moment.

**Comment by JaminShanti** [comment]
Does the updated time come from JIRA?  I would think the bot posts the time into slack as a text value.  Bot gets UTC, converts to preferred time value, posts to channel as text.  Thoughts I can configure what value it gets from JIRA?  wrap it in a Time Zone. I am on the East Coast -4
