### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by liorpesoa** [shaunburdick/slack-jirabot#3]
Hi,

I would love if the slack-jirabot will have the option to show a custom field which is a string and not only the sprint number.
for instance my custom field is a string from the type: Select List (multiple choices)

Thanks,
Lior Pesoa
lior@honeybook.com

**Comment by shaunburdick** [comment]
Sorry this took a while, I got distracted. I added the ability to show any custom fields. Let me know if that meets your requirements.

**Comment by liorpesoa** [comment]
Hi,

Thanks a lot for that!

I've tried using it but with no success.
I tried many options on how to add the custom field.
The custom field is: customfield_10812

Can you give me an example on how it should appear in the config file?

**Comment by shaunburdick** [comment]
Ahhh, it seems TypeScript takes out a lot of my comments. Sorry about that.
The ts file is commented a lot better: https://github.com/shaunburdick/slack-jirabot/blob/master/src/config.default.ts

```
    customFields: {
      // Add any custom fields you would like to display
      // customfield_1xxxx: "Custom Title"
    }
```

I will look into Typescript, pretty sure there is a setting to prevent stripping of comments but I think it has to strip inline comments. I could always add this stuff to the README.md too. I think I will do both.

Let me know if that makes a difference!

**Comment by liorpesoa** [comment]
Thanks.

But i get: [Object object] as result for the custom field

any ideas?

This is the custom field from JIRA URL:
ConfigureCustomField!default.jspa?customFieldId=10812

This is how i put it in the config.js:

 customFields: { customfield_10812: 'Commando' } },

http://www.honeybook.com
-  Lior Pesoa*
  
  HoneyBook, Inc. www.honeybook.com
  
  M: +972.52.3793.574  | 1 Zeitlin, Tel-Aviv

**Comment by shaunburdick** [comment]
Yeah that tells me that customfield_10812 isn't a string. This will really only work on string fields at the moment.

If you want, can you paste the contents of that custom field? (replace any text you don't want people to see with XXXX) 

See: https://docs.atlassian.com/jira/REST/latest/#d2e2563

so hit http://your.jira.instance/rest/api/2/issue/<some test ticket id>
This will give you some JSON output (hopefully), dig through that to find the custom field and it's contents and put it in here.

**Comment by liorpesoa** [comment]
```
"customfield_10812": [
  {
    "self": "
```

https://jira.xxxxxxx/xxxxxx/rest/api/2/customFieldOption/10410",
        "value": "Active",
        "id": "10410"
      }

http://www.honeybook.com
-  Lior Pesoa*
  
  HoneyBook, Inc. www.honeybook.com
  
  M: +972.52.3793.574  | 1 Zeitlin, Tel-Aviv

**Comment by shaunburdick** [comment]
ok, that's great! I can enhance this to check if it's an object and show the `value` member if that works for you. Are you looking to display 'Active'?

**Comment by liorpesoa** [comment]
Yes.

**Comment by shaunburdick** [comment]
Alright, I'm at work at the moment, I will try to put something together for you tonight.

**Comment by shaunburdick** [comment]
Updated the config. You can now do:

```
    customFields: {
      "customfield_10812.value": "Commando"
    }
```

Give it a try and let me know if that works!  Thanks for your patience!

**Comment by liorpesoa** [comment]
Hi!

Not working :(
I put this:

customFields: {

```
    "customfield_10812.value": "Commando"

    }
```

btw, you have a bug, if you first mistaken and you write the JIRA issue
like this: BLA01033 (instead of BLA-1033)

then you edit the 0 to be -  , the bot crashes

http://www.honeybook.com
-  Lior Pesoa*
  
  HoneyBook, Inc. www.honeybook.com
  
  M: +972.52.3793.574  | 1 Zeitlin, Tel-Aviv

**Comment by shaunburdick** [comment]
Ahhh, I see it now. Your custom field can have more than one value so it's an array.
It would have to be something like `customfield_10812[0].value` which I don't currently support.

I'm not sure there is much I can do about that one, you may need to fork this codebase and change the Sprint logic to meet your specific case.

As for the bug, I was unable to reproduce it in the newest release. I added some extra error checking and it may have happily covered the edit bug.

**Comment by shaunburdick** [comment]
Let me mull on if and how I want to try and support this. We are getting into some pretty gnarly territory if I we to allow array selectors. I could go the quick and dirty way and try an `eval` but it just feels wrong.

**Comment by shaunburdick** [comment]
OK, so I went with it. I am using eval to parse the path structure. If you use the latest (1.4) release you should be able to use `customfield_10812[0].value`.
